# Generated by Django 5.2.10 on 2026-01-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresult',
            name='snapshot',
            field=models.TextField(blank=True, null=True),
        ),
    ]
